# Generated by Django 5.1.5 on 2025-07-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialcause', '0002_resumetemplate_resume_project_experience_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
